server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:                         # 👈 ADD THIS SECTION
    hostname: localhost             # force Eureka to use localhost
    prefer-ip-address: false        # prefer localhost/IP instead of Ina.mshome.net
    instance-id: ${spring.application.name}:${server.port}